error handling asynchronous scenario here best practice error handling asynchronous scenario always error object automatically capture program stacktrace consequently never throw reject literal plain object utils package sapcloudsdkutil there class errorwithcause concatenates error error failed fetch instance destination unable parse jwt authorization header objecterrorwithcause usersdrepossdkjspackagesutilsrcerrorts usersdrepossdkjspackagescoresrcscpcfdestinationservicets processticksandrejections internalprocessnexttickjs runnextticks internalprocessnexttickjs processimmediate timersjs caused error request failed code createerror usersdrepossdkjsnodemodulesaxioslibcorecreateerrorjs settle usersdrepossdkjsnodemodulesaxioslibcoresettlejs incomingmessagehandlestreamend usersdrepossdkjsnodemodulesaxioslibadaptershttpjs incomingmessageemit eventsjs endreadablent streamreadablejs processticksandrejections internalprocessnexttickjs runnextticks internalprocessnexttickjs processimmediate timersjs await without trycatch fine fact following two function behave equivalently function gogetit return axios gethttpsexamplecom thenresp respdata catcherror promiserejectnew erroroh async function gogetit let resp try resp await axiosgethttpsexamplecom catch error throw new erroroh return respdata throwing async function equivalent promisereject possible extend error introduce custom field statuscode something impossible communicate consumer long still promise side note people draw conclusion throw error instead return type like string somethingsomethingdangerzoneerror disagree thats separate discussion